# pyarrow withheld its bundled stubs in 25.0.0 because they were incomplete
# (apache/arrow#50168). Delete this file once the wheels ship them again.

# only referenced through polars' signatures, never constructed here
class Array: ...
class ChunkedArray: ...
class RecordBatch: ...

class Table:
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...
